server:
  servlet:
    context-path: /api

spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:h2:~/db/app_data
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

# Application config

shop:
  strategy: singleLocation